name: google_maps_widget
description: A widget for flutter developers to easily integrate google maps in their apps. It can be used to make polylines from a source to a destination, and also handle realtime driver location on the map if needed.
version: 0.0.1
homepage: https://github.com/rithik-dev/google_maps_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.3
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
