name: google_maps_widget
description: A Flutter package which can be used to make polylines(route) from a source to a destination, and also handle a driver's realtime location (if any) on the map.
version: 0.0.6
homepage: https://github.com/rithik-dev/google_maps_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
